# UDP Discovery constants and utilities
UDP_SERVICE_DISCOVERY_PORT = 50001
UDP_CLIENT_DISCOVERY_PORT  = 4096
UDP_BROADCAST_IP = '192.168.50.255'
HEARTBEAT_INTERVAL_SEC = 30
SERVICE_EXPIRY_MULTIPLIER = 3  # e.g., 3x heartbeat interval
